


# Generated by Django 5.1.6 on 2025-02-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controladora_de_vuelo', models.CharField(max_length=255)),
                ('frame', models.CharField(max_length=255)),
                ('helices', models.IntegerField()),
                ('motores', models.IntegerField()),
                ('transmisores', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('telemetria', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
    ]
