# Generated by Django 5.1.2 on 2025-05-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        # 1) Renombrar id → folio en Usuario
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='folio',
        ),
        # 2) Eliminar el campo contrasena
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        # 3) Renombrar id → folio en Dron
        migrations.RenameField(
            model_name='dron',
            old_name='id',
            new_name='folio',
        ),
    ]
