# Generated by Django 5.1.2 on 2025-05-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_id_to_folio"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoConfirmacion",
            fields=[
                ("folio", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "estado_confirmacion",
            },
        ),
        migrations.CreateModel(
            name="TipoAlerta",
            fields=[
                ("folio", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tipo_alerta",
            },
        ),
        migrations.AlterField(
            model_name="dron",
            name="folio",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="folio",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="dron",
            table="dron",
        ),
        migrations.AlterModelTable(
            name="usuario",
            table="users",
        ),
        migrations.CreateModel(
            name="RutasVuelo",
            fields=[
                ("folio", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField()),
                ("coordenadas", models.JSONField()),
                (
                    "folio_dron",
                    models.ForeignKey(
                        db_column="folio_dron",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dron",
                    ),
                ),
                (
                    "folio_usuario",
                    models.ForeignKey(
                        db_column="folio_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "rutas_vuelo",
            },
        ),
        migrations.CreateModel(
            name="Notificaciones",
            fields=[
                ("folio", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField()),
                ("longitud", models.FloatField()),
                ("latitud", models.FloatField()),
                (
                    "estado_confirmacion",
                    models.ForeignKey(
                        db_column="estado_confirmacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.estadoconfirmacion",
                    ),
                ),
                (
                    "folio_dron",
                    models.ForeignKey(
                        db_column="folio_dron",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dron",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        db_column="tipo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.tipoalerta",
                    ),
                ),
            ],
            options={
                "db_table": "notificaciones",
            },
        ),
    ]
