# Generated by Django 5.1.2 on 2025-05-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_estadoconfirmacion_tipoalerta_alter_dron_folio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificaciones",
            name="frame",
            field=models.CharField(
                default="http://localhost:5173/images/default.jpg", max_length=255
            ),
            preserve_default=False,
        ),
    ]
